include:
  - ./my-agent/compose.livekit.yaml #loads livekit server and related services
services:
  app:
    profiles:
      - devcontainer
    build:
      context: .
      dockerfile: Dockerfile.devcontainer
    env_file:
      - .env
    environment:
      DATABASE_URL: mongodb://mongodb:27017/artaround
    depends_on:
      mongodb:
        condition: service_healthy
      typesense:
        condition: service_healthy
    volumes:
      - .:/workspace:cached
      - node_modules:/workspace/node_modules
    working_dir: /workspace
    ports:
      - '3000:3000'
    command: sleep infinity

  mongodb:
    image: mongo:8
    restart: unless-stopped
    env_file:
      - .env.mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--quiet', '--eval', "db.adminCommand('ping').ok"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
  typesense:
    image: typesense/typesense:30.2
    restart: on-failure
    ports:
      - '8108:8108'
    volumes:
      - typesense_data:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'
    healthcheck:
      test:
        ['CMD-SHELL', 'wget --no-verbose --tries=1 --spider http://localhost:8108/health || exit 1']
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

volumes:
  mongo-data:
  node_modules:
  typesense_data:
