allowBuilds:
  '@livekit/local-inference': true
  onnxruntime-node: true
  protobufjs: true
  sharp: true

onlyBuiltDependencies:
  - '@livekit/local-inference'
  - onnxruntime-node

overrides:
  onnxruntime-common: 1.23.2
  onnxruntime-node: 1.23.2
