// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  "common": {
    "languageSwitcher": {
      "label": "Select Language"
    },
    "navbar": {
      "Marketplace": "Marketplace",
      "Navigator": "Navigator"
    }
  },
  "museum-page": {
    "Hide": "Hide",
    "No description available": "No description available",
    "Show more": "Show more",
    "contents": "contents",
    "info": "info"
  },
  "objects-carousel": {
    "No objects available": "No objects available",
    "See more objects": "See more objects"
  },
  "objects-carousel-card": {
    "No thumbnail available for {{name}}": "No thumbnail available for {{name}}",
    "See more": "See more"
  }
}
