// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  "common": {
    "languageSwitcher": {
      "label": "Select Language"
    },
    "navbar": {
      "Marketplace": "Marketplace",
      "Navigator": "Navigator"
    }
  },
  "museum-page": {
    "Hide": "Hide",
    "No description available": "No description available",
    "Show more": "Show more",
    "contents": "contents",
    "info": "info"
  }
}
