/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    museums: Museum;
    museumThumbnails: MuseumThumbnail;
    museumMaps: MuseumMap;
    objects: Object;
    exhibits: Exhibit;
    contents: Content;
    contentImages: ContentImage;
    forms: Form;
    'form-submissions': FormSubmission;
    redirects: Redirect;
    exports: Export;
    imports: Import;
    'permission-actions': PermissionAction;
    'permission-features': PermissionFeature;
    permissions: Permission;
    roles: Role;
    'roles-permissions': RolesPermission;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    objects: {
      exhibit: 'exhibits';
    };
    contents: {
      objects: 'objects';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    museums: MuseumsSelect<false> | MuseumsSelect<true>;
    museumThumbnails: MuseumThumbnailsSelect<false> | MuseumThumbnailsSelect<true>;
    museumMaps: MuseumMapsSelect<false> | MuseumMapsSelect<true>;
    objects: ObjectsSelect<false> | ObjectsSelect<true>;
    exhibits: ExhibitsSelect<false> | ExhibitsSelect<true>;
    contents: ContentsSelect<false> | ContentsSelect<true>;
    contentImages: ContentImagesSelect<false> | ContentImagesSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    exports: ExportsSelect<false> | ExportsSelect<true>;
    imports: ImportsSelect<false> | ImportsSelect<true>;
    'permission-actions': PermissionActionsSelect<false> | PermissionActionsSelect<true>;
    'permission-features': PermissionFeaturesSelect<false> | PermissionFeaturesSelect<true>;
    permissions: PermissionsSelect<false> | PermissionsSelect<true>;
    roles: RolesSelect<false> | RolesSelect<true>;
    'roles-permissions': RolesPermissionsSelect<false> | RolesPermissionsSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: {
      createCollectionExport: TaskCreateCollectionExport;
      createCollectionImport: TaskCreateCollectionImport;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    username: string;
  };
  login: {
    password: string;
    username: string;
  };
  registerFirstUser: {
    password: string;
    username: string;
  };
  unlock: {
    username: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  isSuperAdmin?: boolean | null;
  roles?: (string | Role)[] | null;
  parent?: (string | null) | User;
  parentPath?: string | null;
  createdBy?: string | null;
  updatedAt: string;
  createdAt: string;
  email?: string | null;
  username: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles".
 */
export interface Role {
  id: string;
  code: string;
  name: string;
  description?: string | null;
  status: 'active' | 'inactive';
  dataScope: 'all' | 'own' | 'hierarchy';
  permissionMatrixDraft?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  createdBy?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title?: string | null;
  slug?: string | null;
  parent?: (string | null) | Page;
  breadcrumbs?:
    | {
        doc?: (string | null) | Page;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "museums".
 */
export interface Museum {
  id: string;
  createdBy?: string | null;
  name: string;
  description?: string | null;
  shortDescription: string;
  accessibility: boolean;
  map?: (string | null) | MuseumMap;
  phone?: string | PhoneNumber | null;
  email?: string | null;
  socials?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  news?:
    | {
        title: string;
        content: string;
        date: string;
        id?: string | null;
      }[]
    | null;
  thumbnails?: (string | MuseumThumbnail)[] | null;
  exhibits?: (string | Exhibit)[] | null;
  objects?: (string | Object)[] | null;
  openingHours?: {
    monday?:
      | {
          opening?: string | null;
          closing?: string | null;
          id?: string | null;
        }[]
      | null;
    tuesday?:
      | {
          opening?: string | null;
          closing?: string | null;
          id?: string | null;
        }[]
      | null;
    wednesday?:
      | {
          opening?: string | null;
          closing?: string | null;
          id?: string | null;
        }[]
      | null;
    thursday?:
      | {
          opening?: string | null;
          closing?: string | null;
          id?: string | null;
        }[]
      | null;
    friday?:
      | {
          opening?: string | null;
          closing?: string | null;
          id?: string | null;
        }[]
      | null;
    saturday?:
      | {
          opening?: string | null;
          closing?: string | null;
          id?: string | null;
        }[]
      | null;
    sunday?:
      | {
          opening?: string | null;
          closing?: string | null;
          id?: string | null;
        }[]
      | null;
    notes?: string | null;
  };
  ticketLink?: string | null;
  ticketInfo: {
    label: string;
    url?: string | null;
  };
  location: {
    address: string;
    city: string;
    /**
     * @minItems 2
     * @maxItems 2
     */
    latlng: [number, number];
  };
  services?: {
    bathrooms?:
      | {
          openingHours?: {
            monday?:
              | {
                  opening?: string | null;
                  closing?: string | null;
                  id?: string | null;
                }[]
              | null;
            tuesday?:
              | {
                  opening?: string | null;
                  closing?: string | null;
                  id?: string | null;
                }[]
              | null;
            wednesday?:
              | {
                  opening?: string | null;
                  closing?: string | null;
                  id?: string | null;
                }[]
              | null;
            thursday?:
              | {
                  opening?: string | null;
                  closing?: string | null;
                  id?: string | null;
                }[]
              | null;
            friday?:
              | {
                  opening?: string | null;
                  closing?: string | null;
                  id?: string | null;
                }[]
              | null;
            saturday?:
              | {
                  opening?: string | null;
                  closing?: string | null;
                  id?: string | null;
                }[]
              | null;
            sunday?:
              | {
                  opening?: string | null;
                  closing?: string | null;
                  id?: string | null;
                }[]
              | null;
            notes?: string | null;
          };
          coordinates: {
            x: number;
            y: number;
          };
          id?: string | null;
        }[]
      | null;
    food?:
      | {
          openingHours?: {
            monday?:
              | {
                  opening?: string | null;
                  closing?: string | null;
                  id?: string | null;
                }[]
              | null;
            tuesday?:
              | {
                  opening?: string | null;
                  closing?: string | null;
                  id?: string | null;
                }[]
              | null;
            wednesday?:
              | {
                  opening?: string | null;
                  closing?: string | null;
                  id?: string | null;
                }[]
              | null;
            thursday?:
              | {
                  opening?: string | null;
                  closing?: string | null;
                  id?: string | null;
                }[]
              | null;
            friday?:
              | {
                  opening?: string | null;
                  closing?: string | null;
                  id?: string | null;
                }[]
              | null;
            saturday?:
              | {
                  opening?: string | null;
                  closing?: string | null;
                  id?: string | null;
                }[]
              | null;
            sunday?:
              | {
                  opening?: string | null;
                  closing?: string | null;
                  id?: string | null;
                }[]
              | null;
            notes?: string | null;
          };
          coordinates: {
            x: number;
            y: number;
          };
          id?: string | null;
        }[]
      | null;
    shop?:
      | {
          openingHours?: {
            monday?:
              | {
                  opening?: string | null;
                  closing?: string | null;
                  id?: string | null;
                }[]
              | null;
            tuesday?:
              | {
                  opening?: string | null;
                  closing?: string | null;
                  id?: string | null;
                }[]
              | null;
            wednesday?:
              | {
                  opening?: string | null;
                  closing?: string | null;
                  id?: string | null;
                }[]
              | null;
            thursday?:
              | {
                  opening?: string | null;
                  closing?: string | null;
                  id?: string | null;
                }[]
              | null;
            friday?:
              | {
                  opening?: string | null;
                  closing?: string | null;
                  id?: string | null;
                }[]
              | null;
            saturday?:
              | {
                  opening?: string | null;
                  closing?: string | null;
                  id?: string | null;
                }[]
              | null;
            sunday?:
              | {
                  opening?: string | null;
                  closing?: string | null;
                  id?: string | null;
                }[]
              | null;
            notes?: string | null;
          };
          coordinates: {
            x: number;
            y: number;
          };
          id?: string | null;
        }[]
      | null;
    infoPoint?:
      | {
          openingHours?: {
            monday?:
              | {
                  opening?: string | null;
                  closing?: string | null;
                  id?: string | null;
                }[]
              | null;
            tuesday?:
              | {
                  opening?: string | null;
                  closing?: string | null;
                  id?: string | null;
                }[]
              | null;
            wednesday?:
              | {
                  opening?: string | null;
                  closing?: string | null;
                  id?: string | null;
                }[]
              | null;
            thursday?:
              | {
                  opening?: string | null;
                  closing?: string | null;
                  id?: string | null;
                }[]
              | null;
            friday?:
              | {
                  opening?: string | null;
                  closing?: string | null;
                  id?: string | null;
                }[]
              | null;
            saturday?:
              | {
                  opening?: string | null;
                  closing?: string | null;
                  id?: string | null;
                }[]
              | null;
            sunday?:
              | {
                  opening?: string | null;
                  closing?: string | null;
                  id?: string | null;
                }[]
              | null;
            notes?: string | null;
          };
          coordinates: {
            x: number;
            y: number;
          };
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "museumMaps".
 */
export interface MuseumMap {
  id: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PhoneNumber".
 */
export interface PhoneNumber {
  /**
   * Phone number in E.164 format. Useful for using in `tel:` links.
   */
  e164: string;
  /**
   * ISO 3166-1 alpha-2 country code.
   *
   * @see https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2.
   * @example "NO"
   */
  regionCode: string;
  /**
   * International calling code.
   *
   * @example "+47"
   */
  callingCode: string;
  /**
   * National format of the phone number.
   */
  national: string;
  /**
   * International format of the phone number.
   */
  international: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "museumThumbnails".
 */
export interface MuseumThumbnail {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exhibits".
 */
export interface Exhibit {
  id: string;
  createdBy?: string | null;
  objects: (string | Object)[];
  coordinates: {
    x: number;
    y: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "objects".
 */
export interface Object {
  id: string;
  createdBy?: string | null;
  name: string;
  description?: string | null;
  exhibit?: {
    docs?: (string | Exhibit)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  contents?: (string | Content)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contents".
 */
export interface Content {
  id: string;
  createdBy?: string | null;
  difficulty: 'easy' | 'medium' | 'hard';
  title: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  readingTimeMins?: number | null;
  copyright: string;
  images?: (string | ContentImage)[] | null;
  objects: {
    docs?: (string | Object)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contentImages".
 */
export interface ContentImage {
  id: string;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?: {
      relationTo: 'pages';
      value: string | Page;
    } | null;
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports".
 */
export interface Export {
  id: string;
  name?: string | null;
  format: 'csv' | 'json';
  limit?: number | null;
  page?: number | null;
  sort?: string | null;
  sortOrder?: ('asc' | 'desc') | null;
  drafts?: ('yes' | 'no') | null;
  selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
  fields?: string[] | null;
  collectionSlug: string;
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports".
 */
export interface Import {
  id: string;
  collectionSlug: string;
  importMode?: ('create' | 'update' | 'upsert') | null;
  matchField?: string | null;
  status?: ('pending' | 'completed' | 'partial' | 'failed') | null;
  summary?: {
    imported?: number | null;
    updated?: number | null;
    total?: number | null;
    issues?: number | null;
    issueDetails?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "permission-actions".
 */
export interface PermissionAction {
  id: string;
  code: string;
  type: 'main' | 'sub';
  sortOrder?: number | null;
  status: 'active' | 'inactive';
  createdBy?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "permission-features".
 */
export interface PermissionFeature {
  id: string;
  code: string;
  sortOrder?: number | null;
  status: 'active' | 'inactive';
  createdBy?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "permissions".
 */
export interface Permission {
  id: string;
  name: string;
  permissionFeature: string | PermissionFeature;
  permissionAction: string | PermissionAction;
  sortOrder?: number | null;
  status: 'active' | 'inactive';
  createdBy?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles-permissions".
 */
export interface RolesPermission {
  id: string;
  role: string | Role;
  permission: string | Permission;
  enabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: string;
  /**
   * The user that the API key is associated with.
   */
  user: string | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  museums?: {
    /**
     * Allow clients to find museums.
     */
    find?: boolean | null;
    /**
     * Allow clients to create museums.
     */
    create?: boolean | null;
    /**
     * Allow clients to update museums.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete museums.
     */
    delete?: boolean | null;
  };
  objects?: {
    /**
     * Allow clients to find objects.
     */
    find?: boolean | null;
    /**
     * Allow clients to create objects.
     */
    create?: boolean | null;
    /**
     * Allow clients to update objects.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete objects.
     */
    delete?: boolean | null;
  };
  exhibits?: {
    /**
     * Allow clients to find exhibits.
     */
    find?: boolean | null;
    /**
     * Allow clients to create exhibits.
     */
    create?: boolean | null;
    /**
     * Allow clients to update exhibits.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete exhibits.
     */
    delete?: boolean | null;
  };
  contents?: {
    /**
     * Allow clients to find contents.
     */
    find?: boolean | null;
    /**
     * Allow clients to create contents.
     */
    create?: boolean | null;
    /**
     * Allow clients to update contents.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete contents.
     */
    delete?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'createCollectionExport' | 'createCollectionImport';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'createCollectionExport' | 'createCollectionImport') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'museums';
        value: string | Museum;
      } | null)
    | ({
        relationTo: 'museumThumbnails';
        value: string | MuseumThumbnail;
      } | null)
    | ({
        relationTo: 'museumMaps';
        value: string | MuseumMap;
      } | null)
    | ({
        relationTo: 'objects';
        value: string | Object;
      } | null)
    | ({
        relationTo: 'exhibits';
        value: string | Exhibit;
      } | null)
    | ({
        relationTo: 'contents';
        value: string | Content;
      } | null)
    | ({
        relationTo: 'contentImages';
        value: string | ContentImage;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'permission-actions';
        value: string | PermissionAction;
      } | null)
    | ({
        relationTo: 'permission-features';
        value: string | PermissionFeature;
      } | null)
    | ({
        relationTo: 'permissions';
        value: string | Permission;
      } | null)
    | ({
        relationTo: 'roles';
        value: string | Role;
      } | null)
    | ({
        relationTo: 'roles-permissions';
        value: string | RolesPermission;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: string | PayloadMcpApiKey;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: string | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: string | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  isSuperAdmin?: T;
  roles?: T;
  parent?: T;
  parentPath?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  username?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "museums_select".
 */
export interface MuseumsSelect<T extends boolean = true> {
  createdBy?: T;
  name?: T;
  description?: T;
  shortDescription?: T;
  accessibility?: T;
  map?: T;
  phone?: T;
  email?: T;
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  news?:
    | T
    | {
        title?: T;
        content?: T;
        date?: T;
        id?: T;
      };
  thumbnails?: T;
  exhibits?: T;
  objects?: T;
  openingHours?:
    | T
    | {
        monday?:
          | T
          | {
              opening?: T;
              closing?: T;
              id?: T;
            };
        tuesday?:
          | T
          | {
              opening?: T;
              closing?: T;
              id?: T;
            };
        wednesday?:
          | T
          | {
              opening?: T;
              closing?: T;
              id?: T;
            };
        thursday?:
          | T
          | {
              opening?: T;
              closing?: T;
              id?: T;
            };
        friday?:
          | T
          | {
              opening?: T;
              closing?: T;
              id?: T;
            };
        saturday?:
          | T
          | {
              opening?: T;
              closing?: T;
              id?: T;
            };
        sunday?:
          | T
          | {
              opening?: T;
              closing?: T;
              id?: T;
            };
        notes?: T;
      };
  ticketLink?: T;
  ticketInfo?:
    | T
    | {
        label?: T;
        url?: T;
      };
  location?:
    | T
    | {
        address?: T;
        city?: T;
        latlng?: T;
      };
  services?:
    | T
    | {
        bathrooms?:
          | T
          | {
              openingHours?:
                | T
                | {
                    monday?:
                      | T
                      | {
                          opening?: T;
                          closing?: T;
                          id?: T;
                        };
                    tuesday?:
                      | T
                      | {
                          opening?: T;
                          closing?: T;
                          id?: T;
                        };
                    wednesday?:
                      | T
                      | {
                          opening?: T;
                          closing?: T;
                          id?: T;
                        };
                    thursday?:
                      | T
                      | {
                          opening?: T;
                          closing?: T;
                          id?: T;
                        };
                    friday?:
                      | T
                      | {
                          opening?: T;
                          closing?: T;
                          id?: T;
                        };
                    saturday?:
                      | T
                      | {
                          opening?: T;
                          closing?: T;
                          id?: T;
                        };
                    sunday?:
                      | T
                      | {
                          opening?: T;
                          closing?: T;
                          id?: T;
                        };
                    notes?: T;
                  };
              coordinates?:
                | T
                | {
                    x?: T;
                    y?: T;
                  };
              id?: T;
            };
        food?:
          | T
          | {
              openingHours?:
                | T
                | {
                    monday?:
                      | T
                      | {
                          opening?: T;
                          closing?: T;
                          id?: T;
                        };
                    tuesday?:
                      | T
                      | {
                          opening?: T;
                          closing?: T;
                          id?: T;
                        };
                    wednesday?:
                      | T
                      | {
                          opening?: T;
                          closing?: T;
                          id?: T;
                        };
                    thursday?:
                      | T
                      | {
                          opening?: T;
                          closing?: T;
                          id?: T;
                        };
                    friday?:
                      | T
                      | {
                          opening?: T;
                          closing?: T;
                          id?: T;
                        };
                    saturday?:
                      | T
                      | {
                          opening?: T;
                          closing?: T;
                          id?: T;
                        };
                    sunday?:
                      | T
                      | {
                          opening?: T;
                          closing?: T;
                          id?: T;
                        };
                    notes?: T;
                  };
              coordinates?:
                | T
                | {
                    x?: T;
                    y?: T;
                  };
              id?: T;
            };
        shop?:
          | T
          | {
              openingHours?:
                | T
                | {
                    monday?:
                      | T
                      | {
                          opening?: T;
                          closing?: T;
                          id?: T;
                        };
                    tuesday?:
                      | T
                      | {
                          opening?: T;
                          closing?: T;
                          id?: T;
                        };
                    wednesday?:
                      | T
                      | {
                          opening?: T;
                          closing?: T;
                          id?: T;
                        };
                    thursday?:
                      | T
                      | {
                          opening?: T;
                          closing?: T;
                          id?: T;
                        };
                    friday?:
                      | T
                      | {
                          opening?: T;
                          closing?: T;
                          id?: T;
                        };
                    saturday?:
                      | T
                      | {
                          opening?: T;
                          closing?: T;
                          id?: T;
                        };
                    sunday?:
                      | T
                      | {
                          opening?: T;
                          closing?: T;
                          id?: T;
                        };
                    notes?: T;
                  };
              coordinates?:
                | T
                | {
                    x?: T;
                    y?: T;
                  };
              id?: T;
            };
        infoPoint?:
          | T
          | {
              openingHours?:
                | T
                | {
                    monday?:
                      | T
                      | {
                          opening?: T;
                          closing?: T;
                          id?: T;
                        };
                    tuesday?:
                      | T
                      | {
                          opening?: T;
                          closing?: T;
                          id?: T;
                        };
                    wednesday?:
                      | T
                      | {
                          opening?: T;
                          closing?: T;
                          id?: T;
                        };
                    thursday?:
                      | T
                      | {
                          opening?: T;
                          closing?: T;
                          id?: T;
                        };
                    friday?:
                      | T
                      | {
                          opening?: T;
                          closing?: T;
                          id?: T;
                        };
                    saturday?:
                      | T
                      | {
                          opening?: T;
                          closing?: T;
                          id?: T;
                        };
                    sunday?:
                      | T
                      | {
                          opening?: T;
                          closing?: T;
                          id?: T;
                        };
                    notes?: T;
                  };
              coordinates?:
                | T
                | {
                    x?: T;
                    y?: T;
                  };
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "museumThumbnails_select".
 */
export interface MuseumThumbnailsSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "museumMaps_select".
 */
export interface MuseumMapsSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "objects_select".
 */
export interface ObjectsSelect<T extends boolean = true> {
  createdBy?: T;
  name?: T;
  description?: T;
  exhibit?: T;
  contents?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exhibits_select".
 */
export interface ExhibitsSelect<T extends boolean = true> {
  createdBy?: T;
  objects?: T;
  coordinates?:
    | T
    | {
        x?: T;
        y?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contents_select".
 */
export interface ContentsSelect<T extends boolean = true> {
  createdBy?: T;
  difficulty?: T;
  title?: T;
  body?: T;
  readingTimeMins?: T;
  copyright?: T;
  images?: T;
  objects?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contentImages_select".
 */
export interface ContentImagesSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports_select".
 */
export interface ExportsSelect<T extends boolean = true> {
  name?: T;
  format?: T;
  limit?: T;
  page?: T;
  sort?: T;
  sortOrder?: T;
  drafts?: T;
  selectionToUse?: T;
  fields?: T;
  collectionSlug?: T;
  where?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports_select".
 */
export interface ImportsSelect<T extends boolean = true> {
  collectionSlug?: T;
  importMode?: T;
  matchField?: T;
  status?: T;
  summary?:
    | T
    | {
        imported?: T;
        updated?: T;
        total?: T;
        issues?: T;
        issueDetails?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "permission-actions_select".
 */
export interface PermissionActionsSelect<T extends boolean = true> {
  code?: T;
  type?: T;
  sortOrder?: T;
  status?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "permission-features_select".
 */
export interface PermissionFeaturesSelect<T extends boolean = true> {
  code?: T;
  sortOrder?: T;
  status?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "permissions_select".
 */
export interface PermissionsSelect<T extends boolean = true> {
  name?: T;
  permissionFeature?: T;
  permissionAction?: T;
  sortOrder?: T;
  status?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles_select".
 */
export interface RolesSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  description?: T;
  status?: T;
  dataScope?: T;
  permissionMatrixDraft?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles-permissions_select".
 */
export interface RolesPermissionsSelect<T extends boolean = true> {
  role?: T;
  permission?: T;
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  museums?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  objects?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  exhibits?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  contents?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionExport".
 */
export interface TaskCreateCollectionExport {
  input: {
    id: string;
    name: string;
    batchSize?: number | null;
    collectionSlug:
      | 'users'
      | 'pages'
      | 'museums'
      | 'museumThumbnails'
      | 'museumMaps'
      | 'objects'
      | 'exhibits'
      | 'contents'
      | 'contentImages'
      | 'forms'
      | 'form-submissions'
      | 'redirects'
      | 'exports'
      | 'imports';
    drafts?: ('yes' | 'no') | null;
    exportCollection: string;
    fields?: string[] | null;
    format: 'csv' | 'json';
    limit?: number | null;
    locale?: string | null;
    maxLimit?: number | null;
    page?: number | null;
    sort?: string | null;
    userCollection?: string | null;
    userID?: string | null;
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionImport".
 */
export interface TaskCreateCollectionImport {
  input: {
    importId: string;
    importCollection: string;
    userID?: string | null;
    userCollection?: string | null;
    batchSize?: number | null;
    debug?: boolean | null;
    defaultVersionStatus?: ('draft' | 'published') | null;
    maxLimit?: number | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}