on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  deploy:
    name: deploy to gualtiero
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1
        env:
          SERVER_PROJECT_PATH: ${{ vars.SERVER_PROJECT_PATH }}
        with:
          username: ${{ secrets.USERNAME }}
          host: ${{ secrets.HOST }}
          key: ${{ secrets.GUALTIERO_SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          envs: SERVER_PROJECT_PATH
          script: |
            whoami
            cd $SERVER_PROJECT_PATH
